pipeline:
  name: CaC Pipeline
  identifier: CaC_Pipeline
  projectIdentifier: DavidStewart
  orgIdentifier: SE_Sandbox
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: dstewartgh
        repoName: cacExample
        build: <+input>
  stages:
    - stage:
        name: "Build "
        identifier: Build
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: Echo
                  identifier: Echo
                  spec:
                    connectorRef: account.DockerHubDiego
                    image: alpine:latest
                    shell: Sh
                    command: echo "Pipeline new branch- change"
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
